data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_path: data/rolling_stones_spotify.csv  # Updated from cleaned_data.csv
  cleaned_dataset_path: data/cleaned_data.csv   # Path where cleaned file will be saved

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_data: artifacts/data_transformation/transformed_data.csv
  raw_data_path: data/rolling_stones_spotify.csv
  processed_data_dir: artifacts/data_transformation
  song_mapping_path: data/song_name_mapping.csv

model_trainer:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/kmeans_model.pkl
  preprocessor_path: artifacts/model_trainer/scaler.pkl
  num_clusters: 5

model_evaluation:
  root_dir: artifacts/model_evaluation
  evaluation_report: artifacts/model_evaluation/evaluation_report.json

recommendation_system:
  root_dir: artifacts/recommendation_system
  clustered_data_path: artifacts/model_trainer/clustered_data.csv
  model_path: artifacts/model_trainer/kmeans_model.pkl






