name: Auto Update Data & Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch New Data & Retrain Model
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}  # Add DAGSHUB_TOKEN
        run: |
          # Fetch new data
          python -c "
          from spotify_recommendation.pipeline.data_ingestion_pipeline import DataUpdatePipeline;
          DataUpdatePipeline(
              client_id='${{ secrets.SPOTIFY_CLIENT_ID }}',
              client_secret='${{ secrets.SPOTIFY_CLIENT_SECRET }}',
              playlist_id='5fCbYbykLg85EVHHYrkgLw'
          ).initiate_data_update()"

          # Retrain the model
          python -c "
          from spotify_recommendation.pipeline.model_trainer_pipeline import ModelTrainerPipeline;
          ModelTrainerPipeline().train_model()"

      - name: Push Updated Model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://lohithkumar01:$HF_TOKEN@huggingface.co/spaces/lohithkumar01/spotify-song-recommendation main