name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is cloned to avoid shallow update errors

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this file exists!

      - name: Set up GitHub authentication
        run: |
          git config --global user.email "vemuboddupalli@gmail.com"
          git config --global user.name "lohithkumar12"

      - name: Ensure Hugging Face Remote Exists
        run: |
          git remote remove hf || echo "No previous remote found"
          git remote add hf https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/lohithkumar01/spotify-song-recommendation.git
          git remote -v  # Verify remote URLs

      - name: Push to Hugging Face Spaces
        run: |
          git pull --rebase hf main || echo "Nothing to pull"
          git push hf main --force  # Full force push to update repo completely
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
