name: Deploy to Hugging Face Spaces 

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure this file exists!

      - name: Check for Changes
        run: |
          git fetch origin main
          git status
          if git diff --quiet; then
            echo "No changes detected, skipping deployment."
            exit 0
          fi

      - name: Set up GitHub authentication
        run: |
          git config --global user.email "vemuboddupalli@gmail.com"
          git config --global user.name "lohithkumar12"

      - name: Push changes to GitHub
        run: |
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No new changes to commit"
          git push https://github.com/lohithkumar12/spotify-song-recommendation.git HEAD:main || echo "No new changes to push"

      - name: Upload to Hugging Face Spaces
        run: |
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/lohithkumar01/spotify-song-recommendation.git || echo "Remote already exists"
          git push hf main --force
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

